# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fibonacci sequence
#' @description Compute item \code{n} of the Fibonacci sequence using c++
#' @param n  item \code{n}
#' @return The value of item \code{n} of the Fibonacci sequence
#' @examples
#' \dontrun{
#' fibC(29)
#' }
#' @export
fibC <- function(n) {
    .Call('_StatComp18039_fibC', PACKAGE = 'StatComp18039', n)
}

